### PR TITLE
updated image_type defaults

### PR DESCRIPTION
**Pull request by ljchang**
It seems like the meta module no longer produces _pFgA_z_ images.  This results in the decoder and the meta module crashing when not specifying a correct image.  I have updated the default to _pFgA_pF=0.50_.  Feel free to change it if you want to go with something else, but definitely update it to something.  This could be really annoying for beginning neurosynth users.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Awesome, thanks for the PR--this is long overdue. But it looks like the tests are failing now and need to be updated; can you take a look? Probably just need to update a string to reflect the change.

**Comment by tyarkoni** [comment]
Oh, hold on, sorry. The issue is actually the the `_z` images are now called something else  ("association_test" maybe? or "specificity"?). I think you just need to rename the target. Don't change it to the pF image, because that will give pretty different results. Sorry about the confusion--I need to a bunch of maintenance on this package...

**Comment by ljchang** [comment]
There are two new ones that I don't recognize [consistency_z, specificity_z].  What are these and which one should I use?  Is it the same as before with just a new name?

**Comment by tyarkoni** [comment]
Consistency is the previous pAgF_z, specificity was previously pFgA_z. Sorry about the confusion. I actually never meant to push those changes to master (was still mulling names over), but a year later, here we are... let me know if you have other suggestions.

**Comment by ljchang** [comment]
ok, switched the names to specificity_z.  I think those names are fine, would be good to have some documentation somewhere.  The tests are passing on my end for these changes in the analysis module.  There is another test failing on the base module, which I don't think is related to these changes.  The tests seem to have been failing before today, but I don't have access to your travisci account to check for sure.

```
______________________________________ TestBase.test_selection_by_peaks ______________________________________

self = <neurosynth.tests.test_base.TestBase testMethod=test_selection_by_peaks>

    def test_selection_by_peaks(self):
        """ Test peak-based Mappable selection. """
        ids = self.real_dataset.get_studies(peaks=[[0, 20, 40]])
>       self.assertEquals(len(ids), 3)
E       AssertionError: 1 != 3

neurosynth/tests/test_base.py:181: AssertionError```

**Comment by tyarkoni** [comment]
Looks good, thanks!

**Comment by adelavega** [comment]
This probably deserves its own issue, but due to changing the name of these outputs, the docs and tutorials are now out of date. e.g.: http://neurosynth.readthedocs.io/en/latest/neurosynth.analysis.meta.html#module-neurosynth.analysis.meta

**Pull request merged**
