### PR TITLE
Clustering refactor

### PR DESCRIPTION
**Pull request by tyarkoni**
Merge refactored clustering code.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Tests are passing locally but not on Travis, probably due to a version issue in one of the dependencies.

**Comment by vsoch** [comment]
They want you to use Docker... come to the Docker!

http://docs.travis-ci.com/user/migrating-from-legacy

**Comment by tyarkoni** [comment]
That's probably worth doing, but it's not a high priority. It's also not the source of this particular issue.

**Comment by vsoch** [comment]
But he's so adorable!

**Pull request merged**
