### PR TITLE
cosmetic improvements

### PR DESCRIPTION
**Pull request by tyarkoni**
Nothing much to see here--just cosmetic/style fixes, plus a much simpler travis-ci config. The latter also fixes the test failures, which were due to out-of-date dependencies.

### CODE REVIEW

**Comment by adelavega** [comment]
What a dramatic branch name for "not much to see here" ;)

**Comment by tyarkoni** [comment]
They're the first non-trivial commits I've made in > 2 years!

**Comment by adelavega** [comment]
Woah, scary. :)

**Comment by vsoch** [comment]
ooh lala! Are these warnings ok?

image

Are we getting a new web interface / something else too? :popcorn: 

:ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: 
:ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: 
:ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: 
:ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: 
:ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: :ice_cream: 

ice cream matrix!

**Comment by tyarkoni** [comment]
Probably? Not sure.

There are no plans to further develop this package--it will be deprecated in favor of [NiMARE](https://github.com/neurostuff/NiMARE) at some point (though NiMARE is not ready for use yet). As for a web interface, that depends on what the NIH council says when they meet in two weeks. If all goes well, there will be a new and dramatically improved (and image-based) web-based engine for annotation and analysis.

**Pull request merged**
